Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad3acd00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/qwiic-i2c/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad3ace80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/qwiic-i2c/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7ddbe0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/qwiic-i2c/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7dd9a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/qwiic-i2c/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7ddbb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/qwiic-i2c/
ERROR: Operation cancelled by user
